# DATA MANIPULATION FOR MODELLING (STANDARD SCALING)

SANTIAGO REYES CASTILLO  
10 DE FEBRERO, 2025  
745826  

In [237]:
import pandas as pd
import statsmodels.api as sm
import numpy as np

In [249]:
data = pd.read_csv("boston.csv")

In [251]:
data.tail()

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
501  0.06263  0.0  11.93   0.0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527  0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076  0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959  0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741  0.0  11.93   0.0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9

In [253]:
data_filtered = data.copy().dropna()

In [255]:
data_filtered.tail()

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
501  0.06263  0.0  11.93   0.0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527  0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076  0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959  0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741  0.0  11.93   0.0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9

In [257]:
data.shape

(506, 14)

In [259]:
data_filtered.shape

(452, 14)

In [8]:
#Elegimos la columna de y y establecemos n
y = np.reshape(data_filtered['MEDV'], [-1,1])
n = len(y)

In [18]:
data_filtered = data_filtered.drop(columns = ['AGE', 'INDUS', 'CRIM'])
x_columns = data_filtered.iloc[:,:-1].values

In [12]:
#Generamos un vector de unos para StatsModels
ones = np.ones([n, 1])

In [22]:
data_filtered['DIS'].describe()

count    452.000000
mean       4.043570
std        2.090492
min        1.129600
25%        2.354750
50%        3.550400
75%        5.401100
max       12.126500
Name: DIS, dtype: float64

In [38]:
standard_data = pd.DataFrame()
standard_data['DIS'] = (data_filtered['DIS'] - data_filtered['DIS'].mean()) / data_filtered['DIS'].std()


In [40]:
standard_data.describe()

DIS
count  4.520000e+02
mean  -9.431983e-17
std    1.000000e+00
min   -1.393916e+00
25%   -8.078578e-01
50%   -2.359111e-01
75%    6.493828e-01
max    3.866520e+00

In [63]:
data_filtered

ZN  CHAS    NOX     RM     DIS  RAD    TAX  PTRATIO       B  LSTAT  \
0    18.0   0.0  0.538  6.575  4.0900    1  296.0     15.3  396.90   4.98   
1     0.0   0.0  0.469  6.421  4.9671    2  242.0     17.8  396.90   9.14   
2     0.0   0.0  0.469  7.185  4.9671    2  242.0     17.8  392.83   4.03   
3     0.0   0.0  0.458  6.998  6.0622    3  222.0     18.7  394.63   2.94   
4     0.0   0.0  0.458  7.147  6.0622    3  222.0     18.7  396.90   5.33   
..    ...   ...    ...    ...     ...  ...    ...      ...     ...    ...   
501   0.0   0.0  0.573  6.593  2.4786    1  273.0     21.0  391.99   9.67   
502   0.0   0.0  0.573  6.120  2.2875    1  273.0     21.0  396.90   9.08   
503   0.0   0.0  0.573  6.976  2.1675    1  273.0     21.0  396.90   5.64   
504   0.0   0.0  0.573  6.794  2.3889    1  273.0     21.0  393.45   6.48   
505   0.0   0.0  0.573  6.030  2.5050    1  273.0     21.0  396.90   7.88   

     MEDV  
0    24.0  
1    21.6  
2    34.7  
3    33.4  
4    36.2  
..    ...  
501  22.4  
502  20.6  
503  23.9  
504  22.0  
505  11.9  

[452 rows x 11 columns]

In [83]:
standard_data = data_filtered.copy()
for i in range(len(data_filtered.columns)):
    name = data_filtered.columns[i]
    mean = data_filtered.iloc[:,i].mean()
    std = data_filtered.iloc[:,i].std()
    standard_data[name] = (data_filtered.iloc[:,i] - mean) / std

In [48]:
data.columns[0]

'CRIM'

In [87]:
standard_data

ZN      CHAS       NOX        RM       DIS       RAD       TAX  \
0    0.217000 -0.289391 -0.024739  0.347120  0.022210 -0.904489 -0.538187   
1   -0.522948 -0.289391 -0.630982  0.116169  0.441776 -0.771925 -0.895028   
2   -0.522948 -0.289391 -0.630982  1.261927  0.441776 -0.771925 -0.895028   
3   -0.522948 -0.289391 -0.727629  0.981486  0.965624 -0.639360 -1.027192   
4   -0.522948 -0.289391 -0.727629  1.204939  0.965624 -0.639360 -1.027192   
..        ...       ...       ...       ...       ...       ...       ...   
501 -0.522948 -0.289391  0.282775  0.374115 -0.748613 -0.904489 -0.690175   
502 -0.522948 -0.289391  0.282775 -0.335236 -0.840027 -0.904489 -0.690175   
503 -0.522948 -0.289391  0.282775  0.948493 -0.897430 -0.904489 -0.690175   
504 -0.522948 -0.289391  0.282775  0.675551 -0.791522 -0.904489 -0.690175   
505 -0.522948 -0.289391  0.282775 -0.470207 -0.735985 -0.904489 -0.690175   

      PTRATIO         B     LSTAT      MEDV  
0   -1.339563  0.394920 -1.049614  0.028331  
1   -0.203232  0.394920 -0.373898 -0.244130  
2   -0.203232  0.335551 -1.203924  1.243053  
3    0.205847  0.361807 -1.380974  1.095470  
4    0.205847  0.394920 -0.992763  1.413341  
..        ...       ...       ...       ...  
501  1.251271  0.323298 -0.287809 -0.153310  
502  1.251271  0.394920 -0.383644 -0.357655  
503  1.251271  0.394920 -0.942409  0.016979  
504  1.251271  0.344595 -0.805966 -0.198720  
505  1.251271  0.394920 -0.578562 -1.345326  

[452 rows x 11 columns]

In [103]:
X = np.hstack((ones, x))

In [95]:
x = data_filtered.drop(columns = ["MEDV"])

In [105]:
X

array([[  1.  ,  18.  ,   0.  , ...,  15.3 , 396.9 ,   4.98],
       [  1.  ,   0.  ,   0.  , ...,  17.8 , 396.9 ,   9.14],
       [  1.  ,   0.  ,   0.  , ...,  17.8 , 392.83,   4.03],
       ...,
       [  1.  ,   0.  ,   0.  , ...,  21.  , 396.9 ,   5.64],
       [  1.  ,   0.  ,   0.  , ...,  21.  , 393.45,   6.48],
       [  1.  ,   0.  ,   0.  , ...,  21.  , 396.9 ,   7.88]])

In [111]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X)

StandardScaler()

In [113]:
X_std = scaler.transform(X)

In [115]:
np.mean(X_std, axis = 0)

array([ 0.00000000e+00, -7.85998602e-18,  6.58273829e-17,  4.71599161e-17,
       -2.67239525e-16, -1.25759776e-16, -6.28798881e-17,  9.43198322e-17,
        2.51519552e-16,  7.70278629e-16, -3.30119413e-16])

In [117]:
np.std(X_std, axis = 0)

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [175]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [273]:
a = data_filtered.index

In [295]:
rand_index = np.random.choice(a, round(len(data_filtered)*.4), replace=False)

In [297]:
rand_index

array([490, 424, 390, 353,  91, 173, 224, 476, 329, 164, 450,  61, 236,
        72, 156, 242, 275, 368, 439, 350, 116, 219, 232, 208, 211, 141,
       216, 421,  69, 345,  57, 231,  56, 167,   4, 137, 358, 195, 442,
       161, 328, 235,  40, 365, 285, 272, 361, 145, 503, 185, 447,  41,
       286, 331, 491, 220, 452, 441, 125, 282, 153, 106, 182, 472,  80,
        83, 310,  76,  66, 114, 146, 352,  94,   0, 117,  90, 483, 169,
       194, 121, 480, 408,  22, 136, 263, 227, 291, 163, 485, 307, 177,
        35, 389, 226, 383, 191, 206, 397, 193, 212, 225,   5, 317, 124,
       123,  70, 105, 221, 267, 265, 344, 150, 500,  81, 296, 130, 356,
         9,  33, 346, 369, 320, 423,  18,  96,  60,  44, 455, 315, 297,
       454, 341,  48, 289, 396, 302, 203, 112, 256, 332, 474, 349, 171,
       135,  86, 122, 210, 280, 462, 213,  63,  16, 471, 186, 402, 484,
       132, 326, 360,   1,  14, 229,  39,  32,  37, 314, 174, 467,  17,
       139, 505, 347,  43, 459, 495, 166, 234, 481, 168, 370, 31

In [279]:
sample = data.iloc[rand_index, :]
sample

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
123  0.15038   0.0  25.65   0.0  0.581  5.856  97.0  1.9444    2  188.0   
83   0.03551  25.0   4.86   0.0  0.426  6.167  46.7  5.4007    4  281.0   
194  0.01439  60.0   2.93   0.0  0.401  6.604  18.8  6.2196    1  265.0   
81   0.04462  25.0   4.86   0.0  0.426  6.619  70.4  5.4007    4  281.0   
185  0.06047   0.0   2.46   0.0  0.488  6.153  68.8  3.2797    3  193.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
492  0.11132   0.0  27.74   0.0  0.609  5.983  83.5  2.1099    4  711.0   
44   0.12269   0.0   6.91   0.0  0.448  6.069  40.0  5.7209    3  233.0   
254  0.04819  80.0   3.64   0.0  0.392  6.108  32.0  9.2203    1  315.0   
196  0.04011  80.0   1.52   0.0  0.404  7.287  34.1  7.3090    2  329.0   
452  5.09017   0.0  18.10   0.0  0.713  6.297  91.8  2.3682   24  666.0   

     PTRATIO       B  LSTAT  MEDV  
123     19.1  370.31  25.41  17.3  
83      19.0  390.64   7.51  22.9  
194     15.6  376.70   4.38  29.1  
81      19.0  395.63   7.22  23.9  
185     17.8  387.11  13.15  29.6  
..       ...     ...    ...   ...  
492     20.1  396.90  13.35  20.1  
44      17.9  389.39   9.55  21.2  
254     16.4  392.89   6.57  21.9  
196     12.6  396.90   4.08  33.3  
452     20.2  385.09  17.27  16.1  

[181 rows x 14 columns]

In [281]:
test = data_filtered.copy()
test = test.drop(index = rand_index)

In [283]:
test

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222.0   
7    0.14455  12.5   7.87   0.0  0.524  6.172  96.1  5.9505    5  311.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
498  0.23912   0.0   9.69   0.0  0.585  6.019  65.3  2.4091    6  391.0   
499  0.17783   0.0   9.69   0.0  0.585  5.569  73.5  2.3999    6  391.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
7       15.2  396.90  19.15  27.1  
..       ...     ...    ...   ...  
498     19.2  396.90  12.92  21.2  
499     19.2  395.77  15.10  17.5  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  

[271 rows x 14 columns]